### ISSUE TITLE
Can't send post to help.nextcloud.com - Internal error 500

### ISSUE THREAD

**Issue by CedricGoby** [nextcloud/nextcloud.com#1286]
Hi,
I Can't create a new thread or answer to a thread on help.nextcloud.com.
I get "500 Internal error"
Thanks for your help

![Capture d’écran_2020-05-14_15-05-27](https://user-images.githubusercontent.com/17612749/81942448-678edd00-95fa-11ea-95e4-f1b91e6b332c.png)
![Capture d’écran_2020-05-14_15-05-54](https://user-images.githubusercontent.com/17612749/81942440-66f64680-95fa-11ea-9d54-efc26e2dfe2d.png)

**Comment by jospoortvliet** [comment]
I am guessing this was a temporary error and has been resolved?

**Comment by CedricGoby** [comment]
No, I just tried to add a new post now and the error still occurs, 
I tried with Firefox and Brave with adblock deactivated, I have also deleted cookies in both browsers.

![Capture d’écran_2020-05-18_06-57-34](https://user-images.githubusercontent.com/17612749/82175816-3ef63400-98d5-11ea-8dfd-6a0ec2eee0fe.png)

**Comment by tflidd** [comment]
I didn't see issues using the forum the last days. I'm using the forum from European networks at CET (UTC+2), perhaps some maintenance work?

**Comment by CedricGoby** [comment]
I tried from another laptop, with another OS (Windows 10) and from another network and the same error still occur.
I'm also an European.
If no one else complains, this error is probably linked to my account but who can help me ?

**Comment by jospoortvliet** [comment]
Gimme your account name, I'll see if something is up ;-)

**Comment by CedricGoby** [comment]
I just tried again to check but still no luck...
My account name is NextUser
Thanks

**Comment by jospoortvliet** [comment]
So I checked your user account - I see nothing odd in the admin settings, but maybe you spot something:
![Admin_-_Nextcloud_community_-_2020-05-27_13 46 25](https://user-images.githubusercontent.com/551757/83015571-e7686e80-a020-11ea-8cd6-36b8ecbe5928.png)

Then I tried to impersonate you (oh yeah, I did, and even liked my own welcome post from your account... :imp: ) and saw no issues either... super weird... Sorry, I just don't know what else I could do to help :cry:

**Comment by CedricGoby** [comment]
Glad you give me my personality back :smile: 

Maybe I've got something for you about my account.

I can login to help.nextcloud.com with
- My user name (NextUser)
- My professional email address (@inra.fr, this one is used in the account preferences)
- My personnal email adress (@free.fr)

Each login give me the identity of "NextUser".

I figured this out because I wanted to create a new account with my personal email address to test my issue... and the system told me that this email address was already in use.

Something weird here is that the first two logins have the same password, but the third login is using another password... but lead to the same "NextUser" account.

With the first two logins I can view the "NextUser" account preferences.

![image](https://user-images.githubusercontent.com/17612749/83661592-a2b37900-a5c6-11ea-95a9-f55226568eb7.png)

But when I use the third login I cannot access the "NextUser" account preferences because there is no link.

![image](https://user-images.githubusercontent.com/17612749/83661866-0b9af100-a5c7-11ea-89c2-d5537f7ec5ec.png)

Maybe there is a shadow account somewhere which causes trouble ? You could locate this account with the email address @free.fr.

If it's possible you could also have a look to the server logs about error 500 around mercredi 3 juin 2020, 16:35:53 (UTC+0000), I have tried to post a dozen times and the error 500 was there every time.

Have a nice day.

**Comment by tflidd** [comment]
The strange thing when I search for the NextUser, I can find two profiles:
![grafik](https://user-images.githubusercontent.com/8111200/85210431-20ee7a00-b340-11ea-88cd-5d6f56de83c4.png)

If I enter the profile, I end up on the same page. Not sure if something got wrong, perhaps with different authentication backends. I don't have admin rights to see your mail address neither can I check the logs. We could perhaps just delete the user and you try to create the account again. Since there is nothing posted, we don't destroy anything.

**Comment by tflidd** [comment]
sorry, there has been some activity on the second accout (the one with avatar):
![grafik](https://user-images.githubusercontent.com/8111200/85210579-63fd1d00-b341-11ea-89ba-e64f9cd922a2.png)

**Comment by tflidd** [comment]
I renamed your original account, then I could access the second account with 0 posts, I deleted this account, then renamed your account to the original name. Can you try again?

**Comment by CedricGoby** [comment]
Yes, that's fixed.

I could send my post, see here : https://help.nextcloud.com/t/what-is-the-right-way-to-dump-the-database-regarding-character-and-collation/85319

But I can't explain the activity, as I was even not logged in at the time of the activity...
Maybe it's because you have entered my account. Please send me a PM if you think there is something malicious.

Anyway, thank you very much !
