### ISSUE TITLE
Website in german has overlapping menu entries

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/nextcloud.com#948]
Set germans as website language and you will see:

<img width="1001" alt="bildschirmfoto 2018-09-08 um 10 06 28" src="https://user-images.githubusercontent.com/2069590/45251962-4cf96080-b34f-11e8-9c45-23c882bc6a88.png">

Not sure if we need to shorten german translation or the menu item width can be fixed.

**Comment by rakekniven** [comment]
Moved from here: https://github.com/nextcloud/website/issues/9

**Comment by MariusBluem** [comment]
Known with some resolutions. Will be solved with upcoming changes @jospoortvliet 😁

**Comment by MariusBluem** [comment]
Done with 
https://github.com/nextcloud/nextcloud.com/commit/213f2e4c9c52ddaa6dd306930b33c12175182cdb by @jospoortvliet ... Thanks!!!

**Comment by rakekniven** [comment]
English website looks different now (there is a gap). German is still the same.

**Comment by MariusBluem** [comment]
The gap is by design and just more visible now. German website will be fixed as soon as the whole translation is done :)

**Comment by jospoortvliet** [comment]
Should be good now... At least most of the time :see_no_evil:
